# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
     
    working_directory: /go/src/github.com/dgruber/qsub
    steps:
      - checkout
      - run: GO111MODULE=on; go build -a -v
      - run: go test -v ./...
      - run:
          name: Code coverage file
          command: go test ./pkg/cli ./pkg/job ./pkg/template -race -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: Code coverage
          command: bash <(curl -s https://codecov.io/bash)
